//Autogenerated file 
var tmp;





tmp = pool.addPlayer('Dede');
tmp.rounds[0].series.push(new Series('Montreal', '7', '2'));
tmp.rounds[0].series.push(new Series('Tampa Bay', '6', '4'));
tmp.rounds[0].series.push(new Series('NY Rangers', '5', '8'));
tmp.rounds[0].series.push(new Series('Washington', '5', '5'));
tmp.rounds[0].series.push(new Series('St-Louis', '4', '7'));
tmp.rounds[0].series.push(new Series('Nashville', '7', '3'));
tmp.rounds[0].series.push(new Series('Anaheim', '5', '6'));
tmp.rounds[0].series.push(new Series('Calgary', '7', '1'));

tmp.rounds[1].series.push(new Series('Montreal', '5', '6'));
tmp.rounds[1].series.push(new Series('NY Rangers', '5', '7'));
tmp.rounds[1].series.push(new Series('Chicago', '5', '8'));
tmp.rounds[1].series.push(new Series('Anaheim', '6', '5'));

tmp.finalistEast = 'NY Rangers';
tmp.finalistWest = 'Anaheim';
tmp.cupWinner = 'NY Rangers';
tmp.calculatePoints(results);



tmp = pool.addPlayer('Jee');
tmp.rounds[0].series.push(new Series('Montreal', '6', '6'));
tmp.rounds[0].series.push(new Series('Detroit', '5', '5'));
tmp.rounds[0].series.push(new Series('NY Rangers', '6', '7'));
tmp.rounds[0].series.push(new Series('NY Islanders', '7', '4'));
tmp.rounds[0].series.push(new Series('St-Louis', '6', '3'));
tmp.rounds[0].series.push(new Series('Chicago', '6', '8'));
tmp.rounds[0].series.push(new Series('Anaheim', '6', '2'));
tmp.rounds[0].series.push(new Series('Calgary', '6', '1'));

tmp.rounds[1].series.push(new Series('Montreal', '7', '6'));
tmp.rounds[1].series.push(new Series('NY Rangers', '6', '5'));
tmp.rounds[1].series.push(new Series('Chicago', '7', '7'));
tmp.rounds[1].series.push(new Series('Anaheim', '6', '8'));

tmp.finalistEast = 'Montreal';
tmp.finalistWest = 'Chicago';
tmp.cupWinner = 'Chicago';
tmp.calculatePoints(results);



tmp = pool.addPlayer('Michou et Tony');
tmp.rounds[0].series.push(new Series('Montreal', '7', '5'));
tmp.rounds[0].series.push(new Series('Tampa Bay', '6', '7'));
tmp.rounds[0].series.push(new Series('NY Rangers', '5', '6'));
tmp.rounds[0].series.push(new Series('NY Islanders', '7', '4'));
tmp.rounds[0].series.push(new Series('St-Louis', '7', '3'));
tmp.rounds[0].series.push(new Series('Chicago', '7', '2'));
tmp.rounds[0].series.push(new Series('Anaheim', '5', '8'));
tmp.rounds[0].series.push(new Series('Calgary', '6', '1'));

tmp.rounds[1].series.push(new Series('Montreal', '7', '5'));
tmp.rounds[1].series.push(new Series('NY Rangers', '5', '8'));
tmp.rounds[1].series.push(new Series('Chicago', '6', '7'));
tmp.rounds[1].series.push(new Series('Anaheim', '6', '6'));

tmp.finalistEast = 'NY Rangers';
tmp.finalistWest = 'Anaheim';
tmp.cupWinner = 'Anaheim';
tmp.calculatePoints(results);



tmp = pool.addPlayer('Michael Kemptner');
tmp.rounds[0].series.push(new Series('Montreal', '7', '4'));
tmp.rounds[0].series.push(new Series('Tampa Bay', '6', '6'));
tmp.rounds[0].series.push(new Series('NY Rangers', '5', '8'));
tmp.rounds[0].series.push(new Series('Washington', '6', '5'));
tmp.rounds[0].series.push(new Series('St-Louis', '6', '1'));
tmp.rounds[0].series.push(new Series('Chicago', '6', '3'));
tmp.rounds[0].series.push(new Series('Winnipeg', '6', '2'));
tmp.rounds[0].series.push(new Series('Calgary', '6', '7'));

tmp.rounds[1].series.push(new Series('Montreal', '7', '5'));
tmp.rounds[1].series.push(new Series('NY Rangers', '6', '8'));
tmp.rounds[1].series.push(new Series('Chicago', '6', '6'));
tmp.rounds[1].series.push(new Series('Anaheim', '6', '7'));

tmp.finalistEast = 'NY Rangers';
tmp.finalistWest = 'Chicago';
tmp.cupWinner = 'Chicago';
tmp.calculatePoints(results);



tmp = pool.addPlayer('Philippe Brazeau');
tmp.rounds[0].series.push(new Series('Montreal', '6', '4'));
tmp.rounds[0].series.push(new Series('Tampa Bay', '5', '7'));
tmp.rounds[0].series.push(new Series('NY Rangers', '5', '8'));
tmp.rounds[0].series.push(new Series('NY Islanders', '6', '3'));
tmp.rounds[0].series.push(new Series('St-Louis', '6', '5'));
tmp.rounds[0].series.push(new Series('Nashville', '6', '2'));
tmp.rounds[0].series.push(new Series('Anaheim', '6', '6'));
tmp.rounds[0].series.push(new Series('Calgary', '6', '1'));

tmp.rounds[1].series.push(new Series('Tampa Bay', '6', '5'));
tmp.rounds[1].series.push(new Series('NY Rangers', '6', '7'));
tmp.rounds[1].series.push(new Series('Chicago', '6', '6'));
tmp.rounds[1].series.push(new Series('Anaheim', '6', '8'));

tmp.finalistEast = 'NY Rangers';
tmp.finalistWest = 'Anaheim';
tmp.cupWinner = 'Anaheim';
tmp.calculatePoints(results);



tmp = pool.addPlayer('Lowrie & Salhautmon');
tmp.rounds[0].series.push(new Series('Montreal', '6', '8'));
tmp.rounds[0].series.push(new Series('Tampa Bay', '6', '5'));
tmp.rounds[0].series.push(new Series('NY Rangers', '5', '6'));
tmp.rounds[0].series.push(new Series('NY Islanders', '6', '1'));
tmp.rounds[0].series.push(new Series('St-Louis', '7', '2'));
tmp.rounds[0].series.push(new Series('Nashville', '5', '7'));
tmp.rounds[0].series.push(new Series('Anaheim', '6', '4'));
tmp.rounds[0].series.push(new Series('Vancouver', '7', '3'));

tmp.rounds[1].series.push(new Series('Montreal', '6', '7'));
tmp.rounds[1].series.push(new Series('NY Rangers', '5', '8'));
tmp.rounds[1].series.push(new Series('Chicago', '6', '5'));
tmp.rounds[1].series.push(new Series('Anaheim', '6', '6'));

tmp.finalistEast = 'Montreal';
tmp.finalistWest = 'Nashville';
tmp.cupWinner = 'Montreal';
tmp.calculatePoints(results);



tmp = pool.addPlayer('Mike');
tmp.rounds[0].series.push(new Series('Montreal', '6', '3'));
tmp.rounds[0].series.push(new Series('Tampa Bay', '5', '6'));
tmp.rounds[0].series.push(new Series('NY Rangers', '5', '8'));
tmp.rounds[0].series.push(new Series('Washington', '6', '7'));
tmp.rounds[0].series.push(new Series('Minnesota', '6', '4'));
tmp.rounds[0].series.push(new Series('Nashville', '5', '5'));
tmp.rounds[0].series.push(new Series('Winnipeg', '7', '1'));
tmp.rounds[0].series.push(new Series('Calgary', '6', '2'));

tmp.rounds[1].series.push(new Series('Montreal', '7', '6'));
tmp.rounds[1].series.push(new Series('NY Rangers', '6', '8'));
tmp.rounds[1].series.push(new Series('Minnesota', '6', '5'));
tmp.rounds[1].series.push(new Series('Anaheim', '5', '7'));

tmp.finalistEast = 'NY Rangers';
tmp.finalistWest = 'Nashville';
tmp.cupWinner = 'NY Rangers';
tmp.calculatePoints(results);



tmp = pool.addPlayer('Faucher');
tmp.rounds[0].series.push(new Series('Montreal', '6', '8'));
tmp.rounds[0].series.push(new Series('Detroit', '5', '7'));
tmp.rounds[0].series.push(new Series('Pittsburgh', '6', '6'));
tmp.rounds[0].series.push(new Series('NY Islanders', '4', '5'));
tmp.rounds[0].series.push(new Series('St-Louis', '6', '4'));
tmp.rounds[0].series.push(new Series('Nashville', '4', '3'));
tmp.rounds[0].series.push(new Series('Anaheim', '4', '1'));
tmp.rounds[0].series.push(new Series('Vancouver', '7', '2'));

tmp.rounds[1].series.push(new Series('Tampa Bay', '7', '5'));
tmp.rounds[1].series.push(new Series('NY Rangers', '6', '7'));
tmp.rounds[1].series.push(new Series('Minnesota', '6', '6'));
tmp.rounds[1].series.push(new Series('Anaheim', '7', '8'));

tmp.finalistEast = 'Montreal';
tmp.finalistWest = 'Anaheim';
tmp.cupWinner = 'Montreal';
tmp.calculatePoints(results);



tmp = pool.addPlayer('Carl Lemay');
tmp.rounds[0].series.push(new Series('Montreal', '6', '7'));
tmp.rounds[0].series.push(new Series('Tampa Bay', '6', '5'));
tmp.rounds[0].series.push(new Series('NY Rangers', '7', '4'));
tmp.rounds[0].series.push(new Series('NY Islanders', '6', '3'));
tmp.rounds[0].series.push(new Series('St-Louis', '6', '6'));
tmp.rounds[0].series.push(new Series('Chicago', '6', '2'));
tmp.rounds[0].series.push(new Series('Winnipeg', '7', '1'));
tmp.rounds[0].series.push(new Series('Vancouver', '5', '8'));

tmp.rounds[1].series.push(new Series('Montreal', '6', '8'));
tmp.rounds[1].series.push(new Series('NY Rangers', '6', '5'));
tmp.rounds[1].series.push(new Series('Chicago', '7', '6'));
tmp.rounds[1].series.push(new Series('Calgary', '7', '7'));

tmp.finalistEast = 'Montreal';
tmp.finalistWest = 'Calgary';
tmp.cupWinner = 'Montreal';
tmp.calculatePoints(results);
